name: zikzak_morphy_annotation
description: Annotations for zikzak_morphy code generation package that provides clean class definitions with copyWith, JSON serialization, toString, equality, and inheritance support
version: 2.0.0
homepage: https://github.com/arrrrny/morphy

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  dartx: ^1.2.0
  json_annotation: ^4.9.0
  quiver: ^3.2.2
