name: morphy
description: Provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 1.0.5
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.1.3 <4.0.0"

#dependency_overrides:
#  morphy_annotation:
#    path: ../morphy_annotation

dependencies:
  morphy_annotation: ^1.0.5
  analyzer: '>=6.0.0 <=7.0.0'
  build: ^2.1.0
  source_gen: ^1.1.1
  dartx: ^1.2.0
  quiver: ^3.2.1
  json_serializable: ^6.3.2
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8